<a href="https://colab.research.google.com/github/sunwoo02/PyTorch-tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [467]:
import torch

In [468]:
import numpy as np

# List

In [469]:
my_list =[[1,2,3,4,5],[6,7,8,9,10]]
my_list[0][2]

3

# NUMPY ARRAYS

In [470]:
np1 = np.random.rand(3,4)
np1

array([[0.41983816, 0.75943492, 0.8912385 , 0.2816701 ],
       [0.02893264, 0.72177693, 0.71295815, 0.1788995 ],
       [0.36489295, 0.15136522, 0.39193   , 0.06201852]])

In [471]:
np1.dtype

dtype('float64')

# Tensors

In [472]:
tensor_2d=torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [473]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [474]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4198, 0.7594, 0.8912, 0.2817],
        [0.0289, 0.7218, 0.7130, 0.1789],
        [0.3649, 0.1514, 0.3919, 0.0620]], dtype=torch.float64)

# Tensor Operation

In [475]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [476]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [477]:
#Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [478]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [479]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [480]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [481]:
#with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [482]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [483]:
my_torch5[1]=4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [484]:
my_torch6
#updated

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [485]:
#Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [486]:
#Grab a specific item
my_torch7[7]

tensor(7)

In [487]:
# Grab a Slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [488]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [489]:
# Return Column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# Tensor Math Operation

In [490]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [491]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [492]:
# Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [493]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [494]:
# Sub Funtion
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [495]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [496]:
# Mul longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [497]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [498]:
#Division longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [499]:
#Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [500]:
# Remainder longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [501]:
# Exponents / power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [502]:
# Exponents/power longhand
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [503]:
# Another way to write longhand
tensor_a.pow(tensor_b)


tensor([    1,    64,  2187, 65536])

In [504]:
tensor_a.add(2)

tensor([3, 4, 5, 6])

In [505]:
tensor_a

tensor([1, 2, 3, 4])

In [506]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [507]:
#tensor_a=tensor_a+tensor_b
tensor_a.add_(tensor_b)
# If there is an underbar behind add, reassignment

tensor([ 6,  8, 10, 12])